external-libraries:
  - charms.rabbitmq_k8s.v0.rabbitmq
  - charms.loki_k8s.v1.loki_push_api
  - charms.tempo_k8s.v2.tracing
  - charms.tempo_k8s.v1.charm_tracing
  - charms.operator_libs_linux.v2.snap
internal-libraries:
  - charms.keystone_k8s.v0.identity_credentials
  - charms.cinder_volume.v0.cinder_volume
  - charms.cinder_ceph_k8s.v0.ceph_access
