external-libraries:
  - charms.data_platform_libs.v0.data_interfaces
  - charms.rabbitmq_k8s.v0.rabbitmq
  - charms.traefik_k8s.v2.ingress
  - charms.certificate_transfer_interface.v0.certificate_transfer
  - charms.loki_k8s.v1.loki_push_api
  - charms.tempo_k8s.v2.tracing
  - charms.tempo_k8s.v1.charm_tracing
internal-libraries:
  - charms.keystone_k8s.v1.identity_service
  - charms.sunbeam_libs.v0.service_readiness
templates:
  - parts/database-connection
  - parts/database-connection-settings
  - parts/section-identity
  - parts/identity-data
  - parts/section-service-user
  - ca-bundle.pem.j2
