---
default_language_version:
  # force all unspecified python hooks to run python3
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ['--fix', 'lf']
        exclude: '.*\.(svg)$'
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-yaml
        files: .*\.(yaml|yml)$
        exclude: zuul.d/secrets.yaml
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        files: |
          (?x)(
            charms/.*/src/
            | charms/.*/tests/
            | ops-sunbeam/ops_sunbeam/
            | ops-sunbeam/tests/unit_tests/
          )
  - repo: https://github.com/csachs/pyproject-flake8.git
    rev: v7.0.0
    hooks:
      - id: pyproject-flake8
        args: [--config=pyproject.toml]
        verbose: true
        files: |
          (?x)(
            charms/.*/src/
            | charms/.*/tests/
            | ops-sunbeam/ops_sunbeam/
            | ops-sunbeam/tests/unit_tests/
          )
  - repo: https://github.com/PyCQA/isort.git
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--check-only", "--diff"]
        files: |
          (?x)(
            charms/.*/src/
            | charms/.*/tests/
            | ops-sunbeam/ops_sunbeam/
            | ops-sunbeam/tests/unit_tests/
          )
  - repo: https://github.com/psf/black.git
    rev: 25.1.0
    hooks:
      - id: black
        args: ["--config=pyproject.toml", "--check", "--diff"]
        additional_dependencies: []
        files: |
          (?x)(
            charms/.*/src/
            | charms/.*/tests/
            | ops-sunbeam/ops_sunbeam/
            | ops-sunbeam/tests/unit_tests/
          )
  - repo: local
    hooks:
      - id: mypy
        name: Run linters (mypy)
        additional_dependencies: [
          "mypy",
          "pyyaml",
          "types-PyYAML",
          "ops",
          "git+https://opendev.org/openstack/charm-ops-interface-ceph-client#egg=interface_ceph_client",
          "tenacity",
          "lightkube"
        ]
        entry: ./run_tox.sh linters
        language: python
