{
 "title": "OpenStack Cloud Overview",
 "tags": [ "is-infra" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "neutron_net",
    "label": "Subnets",
    "query": {
     "query": "openstack_neutron_network_ip_availabilities_total"
    }
   },
   { "name": "hypervisor", "query": { "query": "hypervisor_vcpus_total{}" } },
   { "name": "aggregate", "label": "Availability zone", "query": { "query": "openstack_nova_vcpus_available" } }
  ]
 },
 "panels": [
  {
   "title": "General information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "# OpenStack Cloud Overview\n\n* filter by juju_model (for openstack models) if connected to multiple clouds"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Scheduled VMs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_running_vms{aggregates=~\"$aggregate\"})"
    }
   ]
  },
  {
   "title": "Number of projects",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(group by(tenant) (openstack_nova_limits_instances_max))"
    }
   ]
  },
  {
   "title": "Ceph Storage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(ceph_cluster_total_used_bytes / ceph_cluster_total_bytes) * 100"
    }
   ]
  },
  {
   "title": "CPU Subscription",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_vcpus_used{aggregates=~\"$aggregate\"}) / sum(openstack_nova_vcpus_available{aggregates=~\"$aggregate\"}) * 100"
    }
   ]
  },
  {
   "title": "Mem Subscription",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_memory_used_bytes{aggregates=~\"$aggregate\"}) / sum(openstack_nova_memory_available_bytes{aggregates=~\"$aggregate\"}) * 100"
    }
   ]
  },
  {
   "title": "IPs available in $neutron_net",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(openstack_neutron_network_ip_availabilities_used{subnet_name=\"$neutron_net\"}) / sum(openstack_neutron_network_ip_availabilities_total{subnet_name=\"$neutron_net\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "ceph_cluster_total_used_bytes" }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "ceph_cluster_total_bytes" }
   ]
  },
  {
   "title": "Allocated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_vcpus_used{aggregates=~\"$aggregate\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_vcpus_available{aggregates=~\"$aggregate\"})"
    }
   ]
  },
  {
   "title": "Allocated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_memory_used_bytes{aggregates=~\"$aggregate\"}) / 1e+06"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_memory_available_bytes{aggregates=~\"$aggregate\"}) / 1e+06"
    }
   ]
  },
  {
   "title": "Allocated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(openstack_neutron_network_ip_availabilities_used{subnet_name=\"$neutron_net\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(openstack_neutron_network_ip_availabilities_total{subnet_name=\"$neutron_net\"})"
    }
   ]
  },
  {
   "title": "Free Disk by aggregate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "(sum by(aggregates) (openstack_nova_local_storage_available_bytes * on(hostname) group_left() openstack_placement_resource_allocation_ratio{resourcetype=\"DISK_GB\"} / 1e+09)) - (sum by(aggregates) (openstack_nova_local_storage_used_bytes) / 1e+09)",
     "legendFormat": "{{aggregate}}"
    }
   ]
  },
  {
   "title": "Running VMs by aggregate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(aggregate) (openstack_nova_running_vms{aggregates=~\".+\"})",
     "legendFormat": "{{aggregate}}"
    }
   ]
  },
  {
   "title": "Top instance projects",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(10, count by(tenant_id) (openstack_nova_server_status))",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Instances by state",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by(status) (openstack_nova_server_status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Free RAM GBs per host",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(hostname) (openstack_nova_memory_available_bytes) / 1e+09 - sum by(hostname) (openstack_nova_memory_used_bytes) / 1e+09",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Free disk GBs per host",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(hostname) (openstack_nova_local_storage_available_bytes) / 1e+09 - sum by(hostname) (openstack_nova_local_storage_used_bytes) / 1e+09",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Free vCPUs per host",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(hostname) (openstack_nova_vcpus_available) - sum by(hostname) (openstack_nova_vcpus_used)",
     "legendFormat": "{{hypervisor_hostname}}"
    }
   ]
  }
 ]
}