{
 "title": "OpenStack Compute Overview",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "hypervisor", "query": { "query": "openstack_nova_vcpus_available" } },
   { "name": "project", "query": { "query": "libvirt_domain_info_meta" } },
   {
    "name": "ceph_without_ephemeral",
    "label": "Ceph Shared Storage",
    "query": {
     "query": "query_result(((ceph_cluster_total_bytes or vector(0) > bool(0)) * scalar(stddev(openstack_nova_local_storage_available_bytes) < bool(1e8)) * scalar(abs(sum(ceph_cluster_total_bytes or vector(0)) - max(openstack_nova_local_storage_available_bytes)) < bool(5e9))))"
    }
   }
  ]
 },
 "panels": [
  { "title": "General information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Scheduled VMs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(project_name) (libvirt_domain_info_meta{project_name=~\"$project\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hypervisor CPU Subscription",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_vcpus_used{hostname=~\"$hypervisor.*\"}) / sum(openstack_nova_vcpus_available{hostname=~\"$hypervisor.*\"}) * 100"
    }
   ]
  },
  {
   "title": "Hypervisor Mem Subscription",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_memory_used_bytes{hostname=~\"$hypervisor.*\"}) / sum(openstack_nova_memory_available_bytes{hostname=~\"$hypervisor.*\"}) * 100"
    }
   ]
  },
  {
   "title": "Hypervisor Disk Subscription",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(${ceph_without_ephemeral} * ((ceph_cluster_total_used_bytes or vector(0)) / clamp_min((ceph_cluster_total_bytes or vector(0)), 1) * 100)) + ((1 - ${ceph_without_ephemeral}) * (sum(openstack_nova_local_storage_used_bytes{hostname=~\"$hypervisor.*\"}) / sum(openstack_nova_local_storage_available_bytes{hostname=~\"$hypervisor.*\"}) * 100))"
    }
   ]
  },
  {
   "title": "Allocated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_vcpus_used{hostname=~\"$hypervisor.*\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_vcpus_available{hostname=~\"$hypervisor.*\"})"
    }
   ]
  },
  {
   "title": "Allocated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_memory_used_bytes{hostname=~\"$hypervisor.*\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_memory_available_bytes{hostname=~\"$hypervisor.*\"})"
    }
   ]
  },
  {
   "title": "Allocated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_local_storage_used_bytes{hostname=~\"$hypervisor.*\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(${ceph_without_ephemeral} * (ceph_cluster_total_bytes or vector(0))) + ((1 - ${ceph_without_ephemeral}) * sum(openstack_nova_local_storage_available_bytes{hostname=~\"$hypervisor.*\"}))"
    }
   ]
  },
  {
   "title": "Instances stats",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(libvirt_domain_info_cpu_time_seconds_total[$__rate_interval]) * on(juju_unit, domain) group_left(project_name, instance_name, uuid, flavor) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "libvirt_domain_info_memory_usage_bytes * on(juju_unit, domain) group_left(project_name, instance_name, uuid, flavor) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by(juju_unit, domain) (rate(libvirt_domain_interface_stats_receive_bytes_total[$__rate_interval])) + sum by(juju_unit, domain) (rate(libvirt_domain_interface_stats_transmit_bytes_total[$__rate_interval]))) * on(juju_unit, domain) group_left(project_name, instance_name, uuid, flavor) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by(juju_unit, domain) (rate(libvirt_domain_interface_stats_receive_packets_total[$__rate_interval])) + sum by(juju_unit, domain) (rate(libvirt_domain_interface_stats_transmit_packets_total[$__rate_interval]))) * on(juju_unit, domain) group_left(project_name, instance_name, uuid, flavor) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by(juju_unit, domain) (rate(libvirt_domain_interface_stats_receive_errors_total[$__rate_interval])) + sum by(juju_unit, domain) (rate(libvirt_domain_interface_stats_transmit_errors_total[$__rate_interval]))) * on(juju_unit, domain) group_left(project_name, instance_name, uuid, flavor) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by(juju_unit, domain) (rate(libvirt_domain_interface_stats_receive_drops_total[$__rate_interval])) + sum by(juju_unit, domain) (rate(libvirt_domain_interface_stats_transmit_drops_total[$__rate_interval]))) * on(juju_unit, domain) group_left(project_name, instance_name, uuid, flavor) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by(juju_unit, domain) (rate(libvirt_domain_block_stats_read_requests_total[$__rate_interval])) + sum by(juju_unit, domain) (rate(libvirt_domain_block_stats_write_requests_total[$__rate_interval]))) * on(juju_unit, domain) group_left(project_name, instance_name, uuid, flavor) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by(juju_unit, domain) (rate(libvirt_domain_block_stats_read_bytes_total[$__rate_interval])) + sum by(juju_unit, domain) (rate(libvirt_domain_block_stats_write_bytes_total[$__rate_interval]))) * on(juju_unit, domain) group_left(project_name, instance_name, uuid, flavor) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Time",
   "type": "timeseries",
   "description": "CPU time used by the domain - rate over time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(libvirt_domain_info_cpu_time_seconds_total[$__rate_interval]) * on(juju_unit, domain) group_left(project_name, instance_name, uuid, flavor) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "{{project_name}} | {{instance_name}} | {{uuid}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cumulative Memory Usage",
   "type": "timeseries",
   "description": "Total memory used per hypervisor",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(juju_unit) (libvirt_domain_info_memory_usage_bytes)",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Instance Memory Usage",
   "type": "timeseries",
   "description": "Instance memory usage, stacked",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "libvirt_domain_info_memory_usage_bytes * on(juju_unit, domain) group_left(project_name, instance_name, uuid, flavor) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "{{project_name}} | {{instance_name}} | {{uuid}}"
    }
   ]
  },
  {
   "title": "Max Instance Memory",
   "type": "table",
   "description": "Maximum allowed memory per instance",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "libvirt_domain_info_maximum_memory_bytes * on(juju_unit, domain) group_left(project_name, instance_name, uuid, flavor) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Instance Network Throughput",
   "type": "timeseries",
   "description": "Network traffic in bytes, rate over time, receive/transmit per instance, cumulative over all interfaces",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(juju_unit, domain) (rate(libvirt_domain_interface_stats_receive_bytes_total[$__rate_interval])) * on(juju_unit, domain) group_left(project_name, instance_name, uuid, flavor) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "rx: {{project_name}} | {{instance_name}} | {{uuid}}"
    },
    {
     "expr": "sum by(juju_unit, domain) (rate(libvirt_domain_interface_stats_transmit_bytes_total[$__rate_interval])) * on(juju_unit, domain) group_left(project_name, instance_name, uuid, flavor) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "tx: {{project_name}} | {{instance_name}} | {{uuid}}"
    }
   ]
  },
  {
   "title": "Instance Packet Rate",
   "type": "timeseries",
   "description": "Network traffic in packets, rate over time, receive/transmit per instance, cumulative over all interfaces",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(juju_unit, domain) (rate(libvirt_domain_interface_stats_receive_packets_total[$__rate_interval])) * on(juju_unit, domain) group_left(project_name, instance_name, uuid, flavor) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "rx: {{project_name}} | {{instance_name}} | {{uuid}}"
    },
    {
     "expr": "sum by(juju_unit, domain) (rate(libvirt_domain_interface_stats_transmit_packets_total[$__rate_interval])) * on(juju_unit, domain) group_left(project_name, instance_name, uuid, flavor) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "tx: {{project_name}} | {{instance_name}} | {{uuid}}"
    }
   ]
  },
  {
   "title": "Cumulative Network Throughput",
   "type": "timeseries",
   "description": "Total network throughput rates per hypervisor, rate over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(juju_unit) (rate(libvirt_domain_interface_stats_receive_bytes_total[$__rate_interval]))",
     "legendFormat": "rx: {{juju_unit}}"
    },
    {
     "expr": "sum by(juju_unit) (rate(libvirt_domain_interface_stats_transmit_bytes_total[$__rate_interval]))",
     "legendFormat": "tx: {{juju_unit}}"
    }
   ]
  },
  {
   "title": "Cumulative Packet Rate",
   "type": "timeseries",
   "description": "Total network throughput rates per hypervisor, rate over time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(juju_unit) (rate(libvirt_domain_interface_stats_receive_packets_total[$__rate_interval]))",
     "legendFormat": "rx: {{juju_unit}}"
    },
    {
     "expr": "sum by(juju_unit) (rate(libvirt_domain_interface_stats_transmit_packets_total[$__rate_interval]))",
     "legendFormat": "tx: {{juju_unit}}"
    }
   ]
  },
  {
   "title": "Instance Errors and Drops",
   "type": "timeseries",
   "description": "Instance errors and drops, transmit and receive. Rate over time",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(juju_unit, domain) (rate(libvirt_domain_interface_stats_receive_errors_total[$__rate_interval])) * on(juju_unit, domain) group_left(project_name, instance_name, uuid, flavor) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "rx err: {{project_name}} | {{instance_name}} | {{uuid}}"
    },
    {
     "expr": "sum by(juju_unit, domain) (rate(libvirt_domain_interface_stats_transmit_errors_total[$__rate_interval])) * on(juju_unit, domain) group_left(project_name, instance_name, uuid, flavor) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "tx err: {{project_name}} | {{instance_name}} | {{uuid}}"
    },
    {
     "expr": "sum by(juju_unit, domain) (rate(libvirt_domain_interface_stats_receive_drops_total[$__rate_interval])) * on(juju_unit, domain) group_left(project_name, instance_name, uuid, flavor) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "rx drop: {{project_name}} | {{instance_name}} | {{uuid}}"
    },
    {
     "expr": "sum by(juju_unit, domain) (rate(libvirt_domain_interface_stats_transmit_drops_total[$__rate_interval])) * on(juju_unit, domain) group_left(project_name, instance_name, uuid, flavor) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "tx drop: {{project_name}} | {{instance_name}} | {{uuid}}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {}
   ]
  },
  {
   "title": "IOPS Read",
   "type": "timeseries",
   "description": "Instance block dev read request rate over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(juju_unit, domain, target_device) (rate(libvirt_domain_block_stats_read_requests_total[$__rate_interval])) * on(juju_unit, domain) group_left(project_name, instance_name, uuid, flavor) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "{{project_name}} | {{instance_name}} | {{uuid}} | {{target_device}}"
    }
   ]
  },
  {
   "title": "IOPS Write",
   "type": "timeseries",
   "description": "Instance block dev write request rate over time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(juju_unit, domain, target_device) (rate(libvirt_domain_block_stats_write_requests_total[$__rate_interval])) * on(juju_unit, domain) group_left(project_name, instance_name, uuid, flavor) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "{{project_name}} | {{instance_name}} | {{uuid}} | {{target_device}}"
    }
   ]
  },
  {
   "title": "Throughput Read",
   "type": "timeseries",
   "description": "Instance block device read bytes rate over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(juju_unit, domain, target_device) (rate(libvirt_domain_block_stats_read_bytes_total[$__rate_interval])) * on(juju_unit, domain) group_left(project_name, instance_name, uuid, flavor) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "{{project_name}} | {{instance_name}} | {{uuid}} | {{target_device}}"
    }
   ]
  },
  {
   "title": "Throughput Write",
   "type": "timeseries",
   "description": "Instance block device write bytes rate over time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(juju_unit, domain, target_device) (rate(libvirt_domain_block_stats_write_bytes_total[$__rate_interval])) * on(juju_unit, domain) group_left(project_name, instance_name, uuid, flavor) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "{{project_name}} | {{instance_name}} | {{uuid}} | {{target_device}}"
    }
   ]
  }
 ]
}