{
 "title": "[juju] OpenStack Hypervisor Overview",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cloud",
    "query": {
     "query": "openstack_exporter_cache_age_seconds"
    }
   },
   {
    "name": "hypervisor",
    "query": {
     "query": "hypervisor_vcpus_total{cloud=\"$cloud\"}"
    }
   },
   {
    "name": "project",
    "query": {
     "query": "libvirt_domain_info_meta{dns_name=~\"$hypervisor\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "General information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nova Service status",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "hypervisor_schedulable_instances_capacity{cloud=~\"$cloud\", hypervisor_hostname=~\"$hypervisor.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scheduled VMs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(dns_name, project_name) (libvirt_domain_info_meta{dns_name=~\"$hypervisor.*\",project_name=~\"$project\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hypervisor CPU Subscription",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(hypervisor_vcpus_used{cloud=~\"$cloud\",hypervisor_hostname=~\"$hypervisor.*\"}) / sum(hypervisor_vcpus_total{cloud=~\"$cloud\",hypervisor_hostname=~\"$hypervisor.*\"}) * 100"
    }
   ]
  },
  {
   "title": "Hypervisor Mem Subscription",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(hypervisor_memory_mbs_used{cloud=~\"$cloud\",hypervisor_hostname=~\"$hypervisor.*\"}) / sum(hypervisor_memory_mbs_total{cloud=~\"$cloud\",hypervisor_hostname=~\"$hypervisor.*\"}) * 100"
    }
   ]
  },
  {
   "title": "Hypervisor Disk Subscription",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(hypervisor_disk_gbs_used{cloud=~\"$cloud\",hypervisor_hostname=~\"$hypervisor.*\"}) / sum(hypervisor_disk_gbs_total{cloud=~\"$cloud\",hypervisor_hostname=~\"$hypervisor.*\"}) * 100"
    }
   ]
  },
  {
   "title": "Allocated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(hypervisor_vcpus_used{cloud=~\"$cloud\",hypervisor_hostname=~\"$hypervisor.*\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(hypervisor_vcpus_total{cloud=~\"$cloud\",hypervisor_hostname=~\"$hypervisor.*\"})"
    }
   ]
  },
  {
   "title": "Allocated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(hypervisor_memory_mbs_used{cloud=~\"$cloud\",hypervisor_hostname=~\"$hypervisor.*\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(hypervisor_memory_mbs_total{cloud=~\"$cloud\",hypervisor_hostname=~\"$hypervisor.*\"})"
    }
   ]
  },
  {
   "title": "Allocated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(hypervisor_disk_gbs_used{cloud=~\"$cloud\",hypervisor_hostname=~\"$hypervisor.*\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(hypervisor_disk_gbs_total{cloud=~\"$cloud\",hypervisor_hostname=~\"$hypervisor.*\"})"
    }
   ]
  },
  {
   "title": "Hypervisor Stats",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "system_load5{dns_name=~\"$hypervisor.*\"} / system_n_cpus{dns_name=~\"$hypervisor.*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "system_load15{dns_name=~\"$hypervisor.*\"} / system_n_cpus{dns_name=~\"$hypervisor.*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "system_uptime{dns_name=~\"$hypervisor.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instances stats",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "rate(libvirt_domain_info_cpu_time_seconds_total{dns_name=~\"$hypervisor.*\"}[2m]) * on(dns_name, domain) group_left(project_name, instance_name, uuid) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "libvirt_domain_info_memory_usage_bytes{dns_name=~\"$hypervisor.*\"} * on(dns_name, domain) group_left(project_name, instance_name, uuid) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by(dns_name, domain) (rate(libvirt_domain_interface_stats_receive_bytes_total{dns_name=~\"$hypervisor.*\"}[2m])) + sum by(dns_name, domain) (rate(libvirt_domain_interface_stats_transmit_bytes_total{dns_name=~\"$hypervisor.*\"}[2m]))) * on(dns_name, domain) group_left(project_name, instance_name, uuid) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by(dns_name, domain) (rate(libvirt_domain_interface_stats_receive_packets_total{dns_name=~\"$hypervisor.*\"}[2m])) + sum by(dns_name, domain) (rate(libvirt_domain_interface_stats_transmit_packets_total{dns_name=~\"$hypervisor.*\"}[2m]))) * on(dns_name, domain) group_left(project_name, instance_name, uuid) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by(dns_name, domain) (rate(libvirt_domain_interface_stats_receive_errors_total{dns_name=~\"$hypervisor.*\"}[2m])) + sum by(dns_name, domain) (rate(libvirt_domain_interface_stats_transmit_errors_total{dns_name=~\"$hypervisor.*\"}[2m]))) * on(dns_name, domain) group_left(project_name, instance_name, uuid) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by(dns_name, domain) (rate(libvirt_domain_interface_stats_receive_drops_total{dns_name=~\"$hypervisor.*\"}[2m])) + sum by(dns_name, domain) (rate(libvirt_domain_interface_stats_transmit_drops_total{dns_name=~\"$hypervisor.*\"}[2m]))) * on(dns_name, domain) group_left(project_name, instance_name, uuid) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by(dns_name, domain) (rate(libvirt_domain_block_stats_read_requests_total{dns_name=~\"$hypervisor.*\"}[2m])) + sum by(dns_name, domain) (rate(libvirt_domain_block_stats_write_requests_total{dns_name=~\"$hypervisor.*\"}[2m]))) * on(dns_name, domain) group_left(project_name, instance_name, uuid) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by(dns_name, domain) (rate(libvirt_domain_block_stats_read_bytes_total{dns_name=~\"$hypervisor.*\"}[2m])) + sum by(dns_name, domain) (rate(libvirt_domain_block_stats_write_bytes_total{dns_name=~\"$hypervisor.*\"}[2m]))) * on(dns_name, domain) group_left(project_name, instance_name, uuid) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Time",
   "type": "timeseries",
   "description": "CPU time used by the domain, in seconds - rate over 1min",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(libvirt_domain_info_cpu_time_seconds_total{dns_name=~\"$hypervisor.*\"}[2m]) * on(dns_name, domain) group_left(project_name, instance_name, uuid) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "{{project_name}} | {{instance_name}} | {{uuid}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cumulative Memory Usage",
   "type": "timeseries",
   "description": "Total memory used per hypervisor",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(dns_name) (libvirt_domain_info_memory_usage_bytes{dns_name=~\"$hypervisor.*\"})",
     "legendFormat": "{{dns_name}}"
    }
   ]
  },
  {
   "title": "Instance Memory Usage",
   "type": "timeseries",
   "description": "Instance memory usage, stacked",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "libvirt_domain_info_memory_usage_bytes{dns_name=~\"$hypervisor.*\"} * on(dns_name, domain) group_left(project_name, instance_name, uuid) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "{{project_name}} | {{instance_name}} | {{uuid}}"
    }
   ]
  },
  {
   "title": "Max Instance Memory",
   "type": "table",
   "description": "Maximum allowed memory per instance",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "libvirt_domain_info_maximum_memory_bytes{dns_name=~\"$hypervisor.*\"} * on(dns_name, domain) group_left(project_name, instance_name, uuid) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Instance Network Throughput",
   "type": "timeseries",
   "description": "Network traffic in bytes, rate over 1min, receive/transmit per instance, cumulative over all interfaces",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(dns_name, domain) (rate(libvirt_domain_interface_stats_receive_bytes_total{dns_name=~\"$hypervisor.*\"}[2m])) * on(dns_name, domain) group_left(project_name, instance_name, uuid) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "rx: {{project_name}} | {{instance_name}} | {{uuid}}"
    },
    {
     "expr": "sum by(dns_name, domain) (rate(libvirt_domain_interface_stats_transmit_bytes_total{dns_name=~\"$hypervisor.*\"}[2m])) * on(dns_name, domain) group_left(project_name, instance_name, uuid) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "tx: {{project_name}} | {{instance_name}} | {{uuid}}"
    }
   ]
  },
  {
   "title": "Instance Packet Rate",
   "type": "timeseries",
   "description": "Network traffic in packets, rate over 1min, receive/transmit per instance, cumulative over all interfaces",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(dns_name, domain) (rate(libvirt_domain_interface_stats_receive_packets_total{dns_name=~\"$hypervisor.*\"}[2m])) * on(dns_name, domain) group_left(project_name, instance_name, uuid) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "rx: {{project_name}} | {{instance_name}} | {{uuid}}"
    },
    {
     "expr": "sum by(dns_name, domain) (rate(libvirt_domain_interface_stats_transmit_packets_total{dns_name=~\"$hypervisor.*\"}[2m])) * on(dns_name, domain) group_left(project_name, instance_name, uuid) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "tx: {{project_name}} | {{instance_name}} | {{uuid}}"
    }
   ]
  },
  {
   "title": "Cumulative Network Throughput",
   "type": "timeseries",
   "description": "Total network throughput rates per hypervisor, rate over 1min",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(dns_name) (rate(libvirt_domain_interface_stats_receive_bytes_total{dns_name=~\"$hypervisor.*\"}[2m]))",
     "legendFormat": "rx: {{dns_name}}"
    },
    {
     "expr": "sum by(dns_name) (rate(libvirt_domain_interface_stats_transmit_bytes_total{dns_name=~\"$hypervisor.*\"}[2m]))",
     "legendFormat": "tx: {{dns_name}}"
    }
   ]
  },
  {
   "title": "Cumulative Packet Rate",
   "type": "timeseries",
   "description": "Total network throughput rates per hypervisor, rate over 1min",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(dns_name) (rate(libvirt_domain_interface_stats_receive_packets_total{dns_name=~\"$hypervisor.*\"}[2m]))",
     "legendFormat": "rx: {{dns_name}}"
    },
    {
     "expr": "sum by(dns_name) (rate(libvirt_domain_interface_stats_transmit_packets_total{dns_name=~\"$hypervisor.*\"}[2m]))",
     "legendFormat": "tx: {{dns_name}}"
    }
   ]
  },
  {
   "title": "Instance Errors and Drops",
   "type": "timeseries",
   "description": "Instance errors and drops, transmit and receive. Rate over 1min",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(dns_name, domain) (rate(libvirt_domain_interface_stats_receive_errors_total{dns_name=~\"$hypervisor.*\"}[2m])) * on(dns_name, domain) group_left(project_name, instance_name, uuid) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "rx err: {{project_name}} | {{instance_name}} | {{uuid}}"
    },
    {
     "expr": "sum by(dns_name, domain) (rate(libvirt_domain_interface_stats_transmit_errors_total{dns_name=~\"$hypervisor.*\"}[2m])) * on(dns_name, domain) group_left(project_name, instance_name, uuid) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "tx err: {{project_name}} | {{instance_name}} | {{uuid}}"
    },
    {
     "expr": "sum by(dns_name, domain) (rate(libvirt_domain_interface_stats_receive_drops_total{dns_name=~\"$hypervisor.*\"}[2m])) * on(dns_name, domain) group_left(project_name, instance_name, uuid) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "rx drop: {{project_name}} | {{instance_name}} | {{uuid}}"
    },
    {
     "expr": "sum by(dns_name, domain) (rate(libvirt_domain_interface_stats_transmit_drops_total{dns_name=~\"$hypervisor.*\"}[2m])) * on(dns_name, domain) group_left(project_name, instance_name, uuid) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "tx drop: {{project_name}} | {{instance_name}} | {{uuid}}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {}
   ]
  },
  {
   "title": "IOPS Read",
   "type": "timeseries",
   "description": "Instance block dev read request rate over 1min",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(dns_name, domain, target_device) (rate(libvirt_domain_block_stats_read_requests_total{dns_name=~\"$hypervisor.*\"}[2m])) * on(dns_name, domain) group_left(project_name, instance_name, uuid) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "{{project_name}} | {{instance_name}} | {{uuid}} | {{target_device}}"
    }
   ]
  },
  {
   "title": "IOPS Write",
   "type": "timeseries",
   "description": "Instance block dev write request rate over 1min",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(dns_name, domain, target_device) (rate(libvirt_domain_block_stats_write_requests_total{dns_name=~\"$hypervisor.*\"}[2m])) * on(dns_name, domain) group_left(project_name, instance_name, uuid) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "{{project_name}} | {{instance_name}} | {{uuid}} | {{target_device}}"
    }
   ]
  },
  {
   "title": "Throughput Read",
   "type": "timeseries",
   "description": "Instance block device read bytes rate over 1min",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(dns_name, domain, target_device) (rate(libvirt_domain_block_stats_read_bytes_total{dns_name=~\"$hypervisor.*\"}[2m])) * on(dns_name, domain) group_left(project_name, instance_name, uuid) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "{{project_name}} | {{instance_name}} | {{uuid}} | {{target_device}}"
    }
   ]
  },
  {
   "title": "Throughput Write",
   "type": "timeseries",
   "description": "Instance block device write bytes rate over 1min",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(dns_name, domain, target_device) (rate(libvirt_domain_block_stats_write_bytes_total{dns_name=~\"$hypervisor.*\"}[2m])) * on(dns_name, domain) group_left(project_name, instance_name, uuid) libvirt_domain_info_meta{project_name=~\"$project\"}",
     "legendFormat": "{{project_name}} | {{instance_name}} | {{uuid}} | {{target_device}}"
    }
   ]
  }
 ]
}