{
 "title": "[juju] OpenStack Overview",
 "tags": [ "is-infra" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cloud",
    "query": {
     "query": "openstack_exporter_cache_age_seconds"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "openstack_exporter_cache_refresh_duration_seconds{cloud=\"$cloud\"}"
    }
   },
   {
    "name": "neutron_net",
    "label": "External networks",
    "query": {
     "query": "neutron_public_ip_usage{cloud=\"$cloud\",ip_type=\"routerip\"}"
    }
   },
   {
    "name": "hypervisor",
    "query": {
     "query": "hypervisor_vcpus_total{cloud=\"$cloud\"}"
    }
   },
   {
    "name": "hypervisor_status",
    "query": {
     "query": "openstack_nova_vcpus_available{juju_model=\"$juju_model\"}"
    }
   },
   {
    "name": "aggregate",
    "label": "availability zone",
    "query": {
     "query": "hypervisor_vcpus_total{cloud=\"$cloud\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "General information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "# Openstack dashboard: $cloud\n\n* openstack data is cached, currently refreshed every 5 minutes\n* The VM creation / teardown graph doesn't show the values for the builders in scalingstacks because they happen a lot faster than our scrape interval\n* \"Free IPs\" are not owned by any tenant and available for allocation\n* \"Unused IPs\" are owned by a tenant but not currently associated with an instance"
   }
  },
  {
   "title": "Scheduled VMs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(hypervisor_running_vms{cloud=~\"$cloud\", aggregate=~\"$aggregate\"})"
    }
   ]
  },
  {
   "title": "N° of projects",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(nova_quota_instances{type=\"limit\", cloud=~\"$cloud\"})"
    }
   ]
  },
  {
   "title": "Ceph Storage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(ceph_cluster_total_used_bytes/ceph_cluster_total_bytes)*100"
    }
   ]
  },
  {
   "title": "CPU Subscription",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(hypervisor_vcpus_used{cloud=~\"$cloud\", aggregate=~\"$aggregate\"})/sum(hypervisor_vcpus_total{cloud=~\"$cloud\", aggregate=~\"$aggregate\"})*100"
    }
   ]
  },
  {
   "title": "Mem Subscription",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(hypervisor_memory_mbs_used{cloud=~\"$cloud\", aggregate=~\"$aggregate\"})/sum(hypervisor_memory_mbs_total{cloud=~\"$cloud\", aggregate=~\"$aggregate\"})*100"
    }
   ]
  },
  {
   "title": "IPs available in $neutron_net",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(neutron_public_ip_usage{cloud=\"$cloud\", subnet_name=\"$neutron_net\"}) / sum(neutron_net_size{cloud=\"$cloud\", network_name=\"$neutron_net\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "ceph_cluster_total_used_bytes" }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "ceph_cluster_total_bytes" }
   ]
  },
  {
   "title": "Allocated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(hypervisor_vcpus_used{cloud=~\"$cloud\", aggregate=~\"$aggregate\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(hypervisor_vcpus_total{cloud=~\"$cloud\", aggregate=~\"$aggregate\"})"
    }
   ]
  },
  {
   "title": "Allocated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(hypervisor_memory_mbs_used{cloud=~\"$cloud\", aggregate=~\"$aggregate\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(hypervisor_memory_mbs_total{cloud=~\"$cloud\", aggregate=~\"$aggregate\"})"
    }
   ]
  },
  {
   "title": "Allocated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(neutron_public_ip_usage{cloud=\"$cloud\", subnet_name=\"$neutron_net\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 21, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(neutron_net_size{cloud=\"$cloud\",network_name=\"$neutron_net\"})"
    }
   ]
  },
  {
   "title": "Unused IPs (ext-net)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(neutron_net_size{network_name=\"ext-net\",cloud=\"$cloud\"}) - sum(neutron_public_ip_usage{subnet_name=\"ext-net\",cloud=\"$cloud\",ip_status=\"ACTIVE\"})) - (sum(neutron_net_size{network_name=\"ext-net\",cloud=\"$cloud\"}) - sum(neutron_public_ip_usage{subnet_name=\"ext-net\",cloud=\"$cloud\"}))"
    }
   ]
  },
  {
   "title": "Hypervisors stats",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "label_replace(sum by (dns_name, juju_unit)(system_load5{juju_unit=~\".*nova-compute.*\"}), \"short_hostname\", \"$1\", \"dns_name\", \"([^\\\\.]*)\\\\..*\") and on (dns_name)label_replace(hypervisor_running_vms{cloud=~\"$cloud\", aggregate=~\"$aggregate\"}, \"dns_name\", \"$1\", \"hypervisor_hostname\", \"(.*)\")",
     "legendFormat": "{{short_hostname}}"
    },
    {
     "expr": "label_replace(sum by (dns_name, juju_unit)(system_load15{juju_unit=~\".*nova-compute.*\"}), \"short_hostname\", \"$1\", \"dns_name\", \"([^\\\\.]*)\\\\..*\") and on (dns_name)label_replace(hypervisor_running_vms{cloud=~\"$cloud\", aggregate=~\"$aggregate\"}, \"dns_name\", \"$1\", \"hypervisor_hostname\", \"(.*)\")",
     "legendFormat": "{{short_hostname}}"
    },
    {
     "expr": "label_replace(sum by (dns_name, juju_unit)(disk_used{path=~\".*nova/instances.*|.*var.*\",juju_unit=~\".*nova-compute.*\"})/sum by (dns_name, juju_unit)(disk_total{path=~\".*nova/instances.*|.*var.*\",\njuju_unit=~\".*nova-compute.*\"}) * 100, \"short_hostname\", \"$1\", \"dns_name\", \"([^\\\\.]*)\\\\..*\") and on (dns_name)label_replace(hypervisor_running_vms{cloud=~\"$cloud\", aggregate=~\"$aggregate\"}, \"dns_name\", \"$1\", \"hypervisor_hostname\", \"(.*)\")",
     "legendFormat": "{{short_hostname}}"
    },
    {
     "expr": "label_replace(sum by (dns_name)(system_uptime{juju_unit=~\".*nova-compute.*\"}), \"short_hostname\", \"$1\", \"dns_name\", \"([^\\\\.]*)\\\\..*\") and on (dns_name)label_replace(hypervisor_running_vms{cloud=~\"$cloud\", aggregate=~\"$aggregate\"}, \"dns_name\", \"$1\", \"hypervisor_hostname\", \"(.*)\")",
     "legendFormat": "{{short_hostname}}"
    },
    {
     "expr": "label_replace(sum by (hypervisor_hostname)(hypervisor_running_vms{cloud=~\"$cloud\", aggregate=~\"$aggregate\"}), \"short_hostname\", \"$1\", \"hypervisor_hostname\", \"([^\\\\.]*)\\\\..*\")",
     "legendFormat": "{{short_hostname}}"
    },
    {
     "expr": "label_replace(sum by (hypervisor_hostname)(hypervisor_vcpus_used{cloud=~\"$cloud\", aggregate=~\"$aggregate\"})/sum by (hypervisor_hostname)(hypervisor_vcpus_total{cloud=~\"$cloud\", aggregate=~\"$aggregate\"}) *100, \"short_hostname\", \"$1\", \"hypervisor_hostname\", \"([^\\\\.]*)\\\\..*\")",
     "legendFormat": "{{short_hostname}}"
    },
    {
     "expr": "label_replace(sum by (hypervisor_hostname)(hypervisor_memory_mbs_used{cloud=~\"$cloud\", aggregate=~\"$aggregate\"})/sum by (hypervisor_hostname)(hypervisor_memory_mbs_total{cloud=~\"$cloud\", aggregate=~\"$aggregate\"}) *100, \"short_hostname\", \"$1\", \"hypervisor_hostname\", \"([^\\\\.]*)\\\\..*\")",
     "legendFormat": "{{short_hostname}}"
    },
    {
     "expr": "label_replace(count by (hypervisor_hostname, aggregate)(hypervisor_vcpus_total{cloud=~\"$cloud\", aggregate=~\"$aggregate\"}) *100, \"short_hostname\", \"$1\", \"hypervisor_hostname\", \"([^\\\\.]*)\\\\..*\")"
    },
    {
     "expr": "label_replace(sum by (dns_name)(rate(libvirt_domain_interface_stats_receive_bytes_total[1m])) + sum by (dns_name)(rate(libvirt_domain_interface_stats_transmit_bytes_total[1m])), \"short_hostname\", \"$1\", \"dns_name\", \"([^\\\\.]*)\\\\..*\") and on (dns_name)label_replace(hypervisor_running_vms{cloud=~\"$cloud\", aggregate=~\"$aggregate\"}, \"dns_name\", \"$1\", \"hypervisor_hostname\", \"(.*)\")",
     "legendFormat": "{{short_hostname}}"
    }
   ]
  },
  {
   "title": "Projects stats",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "label_replace(sum by (tenant)(nova_instances{cloud=~\"$cloud\"}), \"project\", \"$1\", \"tenant\", \"(.*)\")",
     "legendFormat": "{{project}}"
    },
    {
     "expr": "label_replace(sum by (tenant)(nova_quota_cores{cloud=~\"$cloud\", type=\"in_use\"}), \"project\", \"$1\", \"tenant\", \"(.*)\")",
     "legendFormat": "{{project}}"
    },
    {
     "expr": "label_replace(sum by (tenant)(nova_quota_cores{cloud=~\"$cloud\", type=\"reserved\"}), \"project\", \"$1\", \"tenant\", \"(.*)\")",
     "legendFormat": "{{project}}"
    },
    {
     "expr": "label_replace(sum by (tenant)(nova_quota_cores{cloud=~\"$cloud\", type=\"limit\"}), \"project\", \"$1\", \"tenant\", \"(.*)\")",
     "legendFormat": "{{project}}"
    },
    {
     "expr": "label_replace(sum by (tenant)(nova_quota_cores{cloud=~\"$cloud\", type=\"in_use\"}) / (sum by (tenant)(nova_quota_cores{cloud=~\"$cloud\", type=\"limit\"}) - sum by (tenant)(nova_quota_cores{cloud=~\"$cloud\", type=\"reserved\"}))* 100, \"project\", \"$1\", \"tenant\", \"(.*)\")",
     "legendFormat": "{{project}}"
    },
    {
     "expr": "label_replace(sum by (tenant)(nova_quota_instances{cloud=~\"$cloud\", type=\"in_use\"}), \"project\", \"$1\", \"tenant\", \"(.*)\")",
     "legendFormat": "{{project}}"
    },
    {
     "expr": "label_replace(sum by (tenant)(nova_quota_instances{cloud=~\"$cloud\", type=\"reserved\"}), \"project\", \"$1\", \"tenant\", \"(.*)\")",
     "legendFormat": "{{project}}"
    },
    {
     "expr": "label_replace(sum by (tenant)(nova_quota_instances{cloud=~\"$cloud\", type=\"limit\"}), \"project\", \"$1\", \"tenant\", \"(.*)\")",
     "legendFormat": "{{project}}"
    },
    {
     "expr": "label_replace(sum by (tenant)(nova_quota_instances{cloud=~\"$cloud\", type=\"in_use\"}) / (sum by (tenant)(nova_quota_instances{cloud=~\"$cloud\", type=\"limit\"}) - sum by (tenant)(nova_quota_instances{cloud=~\"$cloud\", type=\"reserved\"}))* 100, \"project\", \"$1\", \"tenant\", \"(.*)\")",
     "legendFormat": "{{project}}"
    },
    {
     "expr": "label_replace(sum by (tenant)(nova_quota_ram_mbs{cloud=~\"$cloud\", type=\"in_use\"}), \"project\", \"$1\", \"tenant\", \"(.*)\")",
     "legendFormat": "{{project}}"
    },
    {
     "expr": "label_replace(sum by (tenant)(nova_quota_ram_mbs{cloud=~\"$cloud\", type=\"reserved\"}), \"project\", \"$1\", \"tenant\", \"(.*)\")",
     "legendFormat": "{{project}}"
    },
    {
     "expr": "label_replace(sum by (tenant)(nova_quota_ram_mbs{cloud=~\"$cloud\", type=\"limit\"}), \"project\", \"$1\", \"tenant\", \"(.*)\")",
     "legendFormat": "{{project}}"
    },
    {
     "expr": "label_replace(sum by (tenant)(nova_quota_ram_mbs{cloud=~\"$cloud\", type=\"in_use\"}) / (sum by (tenant)(nova_quota_ram_mbs{cloud=~\"$cloud\", type=\"limit\"}) - sum by (tenant)(nova_quota_ram_mbs{cloud=~\"$cloud\", type=\"reserved\"}))* 100, \"project\", \"$1\", \"tenant\", \"(.*)\")",
     "legendFormat": "{{project}}"
    },
    {
     "expr": "label_replace(sum by (tenant)(cinder_quota_volume_disks{cloud=~\"$cloud\", type=\"in_use\"}), \"project\", \"$1\", \"tenant\", \"(.*)\")",
     "legendFormat": "{{project}}"
    },
    {
     "expr": "label_replace(sum by (tenant)(cinder_quota_volume_disks{cloud=~\"$cloud\", type=\"reserved\"}), \"project\", \"$1\", \"tenant\", \"(.*)\")",
     "legendFormat": "{{project}}"
    },
    {
     "expr": "label_replace(sum by (tenant)(cinder_quota_volume_disks{cloud=~\"$cloud\", type=\"limit\"}), \"project\", \"$1\", \"tenant\", \"(.*)\")",
     "legendFormat": "{{project}}"
    },
    {
     "expr": "label_replace(sum by (tenant)(cinder_quota_volume_disks{cloud=~\"$cloud\", type=\"in_use\"}) / (sum by (tenant)(cinder_quota_volume_disks{cloud=~\"$cloud\", type=\"limit\"}) - sum by (tenant)(cinder_quota_volume_disks{cloud=~\"$cloud\", type=\"reserved\"}))* 100, \"project\", \"$1\", \"tenant\", \"(.*)\")",
     "legendFormat": "{{project}}"
    },
    {
     "expr": "label_replace(sum by (tenant)(cinder_quota_volume_disk_gigabytes{cloud=~\"$cloud\", type=\"in_use\"}), \"project\", \"$1\", \"tenant\", \"(.*)\")",
     "legendFormat": "{{project}}"
    },
    {
     "expr": "label_replace(sum by (tenant)(cinder_quota_volume_disk_gigabytes{cloud=~\"$cloud\", type=\"reserved\"}), \"project\", \"$1\", \"tenant\", \"(.*)\")",
     "legendFormat": "{{project}}"
    },
    {
     "expr": "label_replace(sum by (tenant)(cinder_quota_volume_disk_gigabytes{cloud=~\"$cloud\", type=\"limit\"}), \"project\", \"$1\", \"tenant\", \"(.*)\")",
     "legendFormat": "{{project}}"
    },
    {
     "expr": "label_replace(sum by (tenant)(cinder_quota_volume_disk_gigabytes{cloud=~\"$cloud\", type=\"in_use\"}) / (sum by (tenant)(cinder_quota_volume_disk_gigabytes{cloud=~\"$cloud\", type=\"limit\"}) - sum by (tenant)(cinder_quota_volume_disk_gigabytes{cloud=~\"$cloud\", type=\"reserved\"}))* 100, \"project\", \"$1\", \"tenant\", \"(.*)\")",
     "legendFormat": "{{project}}"
    },
    {
     "expr": "label_replace(sum by (tenant)(nova_quota_floating_ips{cloud=~\"$cloud\", type=\"in_use\"}), \"project\", \"$1\", \"tenant\", \"(.*)\")",
     "legendFormat": "{{project}}"
    },
    {
     "expr": "label_replace(sum by (tenant)(nova_quota_floating_ips{cloud=~\"$cloud\", type=\"reserved\"}), \"project\", \"$1\", \"tenant\", \"(.*)\")",
     "legendFormat": "{{project}}"
    },
    {
     "expr": "label_replace(sum by (tenant)(nova_quota_floating_ips{cloud=~\"$cloud\", type=\"limit\"}), \"project\", \"$1\", \"tenant\", \"(.*)\")",
     "legendFormat": "{{project}}"
    },
    {
     "expr": "label_replace(sum by (tenant)(nova_quota_floating_ips{cloud=~\"$cloud\", type=\"in_use\"}) / (sum by (tenant)(nova_quota_floating_ips{cloud=~\"$cloud\", type=\"limit\"}) - sum by (tenant)(nova_quota_floating_ips{cloud=~\"$cloud\", type=\"reserved\"}))* 100, \"project\", \"$1\", \"tenant\", \"(.*)\")",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "Free Disk by aggregate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "(sum(hypervisor_disk_gbs_total{aggregate=~\".+\",cloud=\"$cloud\",nova_service_status=\"enabled\"} * on(cloud) group_left openstack_allocation_ratio{cloud=\"$cloud\",resource=\"disk\"}) by(aggregate)) - (sum(hypervisor_disk_gbs_used{aggregate=~\".+\",cloud=\"$cloud\",nova_service_status=\"enabled\"}) by(aggregate))",
     "legendFormat": "{{aggregate}}"
    }
   ]
  },
  {
   "title": "Running VMs by aggregate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(hypervisor_running_vms{aggregate=~\".+\",cloud=\"$cloud\"}) by (aggregate)",
     "legendFormat": "{{aggregate}}"
    }
   ]
  },
  {
   "title": "Top disk projects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, nova_resources_disk_gbs{cloud=\"$cloud\"})",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Top vCPU projects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(10, nova_resources_vcpus{cloud=\"$cloud\"})",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Top RAM projects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, nova_resources_ram_mbs{cloud=\"$cloud\"})",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Top instance projects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(10, nova_instances{cloud=\"$cloud\"})",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Instances by state",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by(instance_state)(nova_instances{cloud=\"$cloud\"})",
     "legendFormat": "{{instance_state}}"
    }
   ]
  },
  {
   "title": "Free RAM GBs per host",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "(sum by (hypervisor_hostname)(hypervisor_memory_mbs_total{cloud=\"$cloud\"})) / 1024 - (sum by (hypervisor_hostname) (hypervisor_memory_mbs_used{cloud=\"$cloud\"}))/1024",
     "legendFormat": "{{hypervisor_hostname}}"
    }
   ]
  },
  {
   "title": "Free disk GBs per host",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 61 },
   "targets": [
    {
     "expr": "sum by (hypervisor_hostname)(hypervisor_disk_gbs_total{cloud=\"$cloud\"}) - sum by (hypervisor_hostname) (hypervisor_disk_gbs_used{cloud=\"$cloud\"})",
     "legendFormat": "{{hypervisor_hostname}}"
    }
   ]
  },
  {
   "title": "Free vCPUs per host",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 61 },
   "targets": [
    {
     "expr": "sum by (hypervisor_hostname)(hypervisor_vcpus_total{cloud=\"$cloud\"}) - sum by (hypervisor_hostname) (hypervisor_vcpus_used{cloud=\"$cloud\"})",
     "legendFormat": "{{hypervisor_hostname}}"
    }
   ]
  },
  { "title": "Openstack Exporter Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Cache age",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "openstack_exporter_cache_age_seconds{cloud=\"$cloud\"}",
     "legendFormat": "Cache age"
    }
   ]
  },
  {
   "title": "Cache refresh duration",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "openstack_exporter_cache_refresh_duration_seconds{cloud=\"$cloud\"}",
     "legendFormat": "Refresh duration"
    }
   ]
  },
  {
   "title": "Scrape duration",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "scrape_duration_seconds{instance=\"$instance\"}",
     "legendFormat": "Scrape duration"
    }
   ]
  }
 ]
}