{
 "title": "OpenStack Project Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "lokids", "label": "Loki datasource", "query": "loki" },
   { "name": "prometheusds", "label": "Prometheus datasource", "query": "prometheus" },
   {
    "name": "Project",
    "query": {
     "query": "openstack_nova_limits_instances_max"
    }
   },
   {
    "name": "Project_id",
    "query": {
     "query": "openstack_nova_limits_memory_max{tenant=\"$Project\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Limits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Instances",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 1, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_nova_limits_instances_max{tenant_id=\"$Project_id\"} - openstack_nova_limits_instances_used{tenant_id=\"$Project_id\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "openstack_nova_limits_instances_used{tenant_id=\"$Project_id\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "VCPUS",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_nova_limits_vcpus_max{tenant_id=\"$Project_id\"} - openstack_nova_limits_vcpus_used{tenant_id=\"$Project_id\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "openstack_nova_limits_vcpus_used{tenant_id=\"$Project_id\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_nova_limits_memory_max{tenant_id=\"$Project_id\"} - openstack_nova_limits_memory_used{tenant_id=\"$Project_id\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "openstack_nova_limits_memory_used{tenant_id=\"$Project_id\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Volumes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_cinder_limits_volume_max_gb{tenant_id=\"$Project_id\"} - openstack_cinder_limits_volume_used_gb{tenant_id=\"$Project_id\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "openstack_cinder_limits_volume_used_gb{tenant_id=\"$Project_id\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "IPs",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (project_id)(openstack_neutron_network_ip_availabilities_total{project_id=\"$Project_id\"}) - sum by (project_id)(openstack_neutron_network_ip_availabilities_used{project_id=\"$Project_id\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "sum by (project_id)(openstack_neutron_network_ip_availabilities_used{project_id=\"$Project_id\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Backups",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_cinder_limits_backup_max_gb{tenant_id=\"$Project_id\"} - openstack_cinder_limits_backup_used_gb{tenant_id=\"$Project_id\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "openstack_cinder_limits_backup_used_gb{tenant_id=\"$Project_id\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Virtual Machines Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Servers list",
   "type": "table",
   "gridPos": { "h": 26, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "openstack_nova_server_status{tenant_id=\"$Project_id\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "openstack_nova_server_local_gb{tenant_id=\"$Project_id\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}