internal-libraries:
  - charms.keystone_k8s.v0.identity_credentials
external-libraries:
  - charms.certificate_transfer_interface.v0.certificate_transfer
  - charms.tempo_coordinator_k8s.v0.tracing
  - charms.tempo_coordinator_k8s.v0.charm_tracing
