- name: collect k8s logs
  args:
    executable: /bin/bash
  shell: |
    snap logs -n all k8s > "{{ zuul.project.src_dir }}/log/k8s-logs.txt"
  become: true
  failed_when: false
- name: get main resources state
  args:
    executable: /bin/bash
  shell: |
    k8s kubectl get all --all-namespaces > "{{ zuul.project.src_dir }}/log/k8s-get-all.txt"
  become: true
  failed_when: false
