- name: test runner packages are installed
  apt:
    name:
      - jq
  become: true
- name: Install sosreport
  community.general.snap:
    name: sosreport
    channel: '{{ sosreport_channel }}'
    classic: '{{ sosreport_classic_mode }}'
  become: true
- name: Create destination for logs
  file:
    path: "{{ zuul.project.src_dir }}/log"
    state: directory
    mode: 0755
- name: collect disk usage
  shell: df -h > {{ zuul.project.src_dir }}/log/df.txt
- name: collect mount list
  shell: mount > {{ zuul.project.src_dir }}/log/mount.txt
- name: collect juju controller related data
  ansible.builtin.include_tasks: collect-juju.yaml
  vars:
    controller: manual
- name: collect juju primary controller
  ansible.builtin.include_tasks: collect-juju.yaml
  when: primary_controller | default(false) | bool
  vars:
    controller: primary
- name: Include k8s tasks
  include_tasks: k8s.yaml
  when: env_type == 'k8s'
- name: Collect k8s pods related to manual controller
  include_tasks: k8s-juju.yaml
  when: env_type == 'k8s'
  vars:
    controller: manual
- name: Collect k8s pods related to primary controller
  include_tasks: k8s-juju.yaml
  when: env_type == 'k8s' and primary_controller | default(false) | bool
  vars:
    controller: primary
- name: Collect sos report
  args:
    executable: /bin/bash
  shell: |
    sudo sosreport.sos report -k networking.timeout=600 --batch --tmp-dir {{ zuul.project.src_dir }}/log/
    sudo chmod 0755 {{ zuul.project.src_dir }}/log/sosreport-*.tar.xz
    sudo chmod 0755 {{ zuul.project.src_dir }}/log/sosreport-*.tar.xz.sha256
- name: fetch juju logs
  synchronize:
    dest: "{{ zuul.executor.log_root }}"
    mode: pull
    src: "{{ zuul.project.src_dir }}/log"
    verify_host: true
    owner: false
    group: false
