external-libraries:
  - charms.data_platform_libs.v0.data_interfaces
  - charms.rabbitmq_k8s.v0.rabbitmq
  - charms.loki_k8s.v1.loki_push_api
  - charms.tempo_k8s.v2.tracing
  - charms.tempo_k8s.v1.charm_tracing
internal-libraries:
  - charms.keystone_k8s.v0.identity_credentials
  - charms.manila_k8s.v0.manila
templates:
  - parts/section-database
  - parts/database-connection
  - parts/database-connection-settings
  - parts/identity-data-id-creds
  - parts/section-oslo-messaging-rabbit
  - parts/section-service-credentials-from-identity-service
  - ca-bundle.pem.j2
