external-libraries:
  - charms.grafana_k8s.v0.grafana_dashboard
  - charms.loki_k8s.v1.loki_push_api
  - charms.certificate_transfer_interface.v0.certificate_transfer
  - charms.tempo_coordinator_k8s.v0.tracing
  - charms.tempo_coordinator_k8s.v0.charm_tracing
internal-libraries:
  - charms.keystone_k8s.v0.identity_resource
templates:
  - ca-bundle.pem.j2
