options:
  debug:
    default: False
    description: Enable debug logging.
    type: boolean
  region:
    default: RegionOne
    description: Space delimited list of OpenStack regions
    type: string
  alarm-history-time-to-live:
    default: -1
    description: |
      Number of seconds that alarm histories are kept in the database for (<= 0
      means forever)
    type: int
  alarm-histories-delete-batch-size:
    default: 0
    description: |
      Number of alarm histories to be deleted in one iteration from the database (0
      means all). (integer value)
    type: int
