- name: Download charms tarball (artifact from watchtower build job)
  include_role:
    name: download-artifact
  vars:
    download_artifact_api: "https://zuul.opendev.org/api/tenant/{{ zuul.tenant }}"
    download_artifact_type: charm_archive
    download_artifact_pipeline: check
    download_artifact_job: charm-build-watchtower
    download_artifact_directory: "{{ zuul.project.src_dir }}"

- name: Extract charms tarball
  unarchive:
    src: "{{ zuul.project.src_dir }}/charms.tar.gz"
    dest: "{{ zuul.project.src_dir }}"
    remote_src: true
