options:
  snap-channel:
    default: "2024.1/edge"
    type: string
  debug:
    default: False
    type: boolean
  resume-on-boot:
    default: True
    description: |
      Whether to resume the guest VMs when the host boots.
    type: boolean
  dns-domain:
    default: "openstack.local"
    type: string
  dns-servers:
    default: "8.8.8.8"
    type: string
  enable-gateway:
    default: False
    type: boolean
  external-bridge:
    default: "br-ex"
    type: string
  external-bridge-address:
    default: "10.20.20.1/24"
    type: string
  physnet-name:
    default: "physnet1"
    type: string
  use-migration-binding:
    default: False
    type: boolean
