options:
  debug:
    default: False
    description: Enable debug logging.
    type: boolean
  os-admin-hostname:
    default: cinder.juju
    description: |
      The hostname or address of the admin endpoints that should be advertised
      in the cinder volume provider.
    type: string
  os-internal-hostname:
    default: cinder.juju
    description: |
      The hostname or address of the internal endpoints that should be advertised
      in the cinder volume provider.
    type: string
  os-public-hostname:
    default: cinder.juju
    description: |
      The hostname or address of the internal endpoints that should be advertised
      in the cinder volume provider.
    type: string
  region:
    default: RegionOne
    description: Name of the OpenStack region
    type: string
