{
 "title": "Capacity Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "lokids", "label": "Loki datasource", "query": "loki" },
   {
    "name": "juju_unit",
    "label": "Juju unit",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_application=~\"$juju_application\"},juju_unit)"
    }
   },
   {
    "name": "juju_application",
    "label": "Juju application",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\"},juju_application)"
    }
   },
   {
    "name": "juju_model_uuid",
    "label": "Juju model uuid",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\"},juju_model_uuid)"
    }
   },
   { "name": "juju_model", "label": "Juju model", "query": { "query": "label_values(up,juju_model)" } },
   { "name": "agent_hostname", "label": "Hostname", "query": { "query": "label_values(agent_hostname)" } },
   { "name": "prometheusds", "label": "Prometheus data source", "query": "prometheus" },
   { "name": "resource_usage_threshold", "label": "Resource Usage Threshold", "query": "50,60,70,80,90,100" },
   { "name": "days_of_estimation", "label": "Days of Estimation", "query": "7,14,30,90,180,360" },
   {
    "name": "total_memory",
    "label": "Total memory",
    "query": {
     "query": "query_result(round(sum by (agent_hostname)(node_memory_MemTotal_bytes{agent_hostname=~\"$agent_hostname\"}) / 1024^3, 0.01))"
    }
   },
   {
    "name": "total_memory_aggregate",
    "label": "Total memory across hosts",
    "query": {
     "query": "query_result(round(sum(node_memory_MemTotal_bytes{agent_hostname=~\"$agent_hostname\"}) / 1024^3, 0.1))"
    }
   },
   {
    "name": "total_disk_machine",
    "label": "Total disk in a host",
    "query": {
     "query": "query_result(round(sum by (agent_hostname)(node_filesystem_size_bytes{agent_hostname=~\"$agent_hostname\", fstype!=\"tmpfs\"} / 1024^3), 0.01))"
    }
   },
   {
    "name": "total_disk_aggregate",
    "label": "Total disk across hosts",
    "query": {
     "query": "query_result(round(sum(node_filesystem_size_bytes{agent_hostname=~\"$agent_hostname\", fstype!=\"tmpfs\"} / 1024^3), 0.01))"
    }
   },
   {
    "name": "cpu_count",
    "label": "CPU count in a host",
    "query": {
     "query": "query_result(count(count(node_cpu_seconds_total{agent_hostname=~\"$agent_hostname\"}) without (mode,instance,job)) without (cpu))"
    }
   },
   {
    "name": "cpu_count_aggregate",
    "label": "CPU count across host",
    "query": {
     "query": "query_result(sum(count(count(node_cpu_seconds_total{agent_hostname=~\"$agent_hostname\"}) without (mode,instance,job)) without (cpu)))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Capacity across hosts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Days until  storage reaches ${resource_usage_threshold}%",
   "type": "stat",
   "description": "Days until  storage reaches ${resource_usage_threshold}%.\nEstimated based on the last ${days_of_estimation} days of data.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min((sum by (agent_hostname) (node_filesystem_size_bytes{agent_hostname=~\"$agent_hostname\", device=~\"/dev/.*\"} * ($resource_usage_threshold / 100) - (node_filesystem_size_bytes{agent_hostname=~\"$agent_hostname\", device=~\"/dev/.*\"}-node_filesystem_avail_bytes{agent_hostname=~\"$agent_hostname\", device=~\"/dev/.*\"}))) \n/ \n((sum by (agent_hostname) (delta((node_filesystem_size_bytes{agent_hostname=~\"$agent_hostname\", device=~\"/dev/.*\"}-node_filesystem_avail_bytes{agent_hostname=~\"$agent_hostname\", device=~\"/dev/.*\"})[${days_of_estimation}d:])) > 0) / $days_of_estimation))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk usage (total size: $total_disk_aggregate GB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((sum by (agent_hostname)(node_filesystem_avail_bytes{agent_hostname=~\"$agent_hostname\", fstype!=\"tmpfs\"} / 1024^3 )\n/\nsum by (agent_hostname) (node_filesystem_size_bytes{agent_hostname=~\"$agent_hostname\", fstype!=\"tmpfs\"} / 1024^3 )) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage (total memory: $total_memory_aggregate GB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((sum(((node_memory_MemUsed_percentage{agent_hostname=~\"$agent_hostname\"}/100) * on(agent_hostname) node_memory_MemTotal_bytes{agent_hostname=~\"$agent_hostname\"}))) / (sum(node_memory_MemTotal_bytes{agent_hostname=~\"$agent_hostname\"}))) * 100",
     "legendFormat": "Total memory used"
    },
    {
     "expr": "((sum((node_memory_HugePages_Total{agent_hostname=~\"$agent_hostname\"} * node_memory_Hugepagesize_bytes{agent_hostname=~\"$agent_hostname\"}) / 1024^3)) / (sum(node_memory_MemTotal_bytes{agent_hostname=~\"$agent_hostname\"} / 1024^3))) * 100",
     "legendFormat": "Memory assigned to hugepages"
    },
    {
     "expr": "((sum((node_memory_HugePages_Total{agent_hostname=~\"$agent_hostname\"} * node_memory_Hugepagesize_bytes{agent_hostname=~\"$agent_hostname\"} - node_memory_HugePages_Free{agent_hostname=~\"$agent_hostname\"} * node_memory_Hugepagesize_bytes{agent_hostname=~\"$agent_hostname\"}) / 1024^3)) / (sum(node_memory_MemTotal_bytes{agent_hostname=~\"$agent_hostname\"} / 1024^3))) * 100",
     "legendFormat": "Used hugepages memory"
    }
   ]
  },
  {
   "title": "CPU Usage (total number of cores: $cpu_count_aggregate)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - avg by (agent_hostname)(rate(node_cpu_seconds_total{agent_hostname=~\"$agent_hostname\", mode=\"idle\"}[5m]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Days until memory reaches ${resource_usage_threshold}%",
   "type": "stat",
   "description": "Days until memory reaches ${resource_usage_threshold}% of capacity.\nEstimated based on the last ${days_of_estimation} days of data.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min((100 * ($resource_usage_threshold / 100) - (node_memory_MemUsed_percentage{agent_hostname=~\"$agent_hostname\"}))\n/ \n((delta((node_memory_MemUsed_percentage{agent_hostname=~\"$agent_hostname\"})[${days_of_estimation}d:]) > 0) / $days_of_estimation))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Days until CPU usage reaches ${resource_usage_threshold}% ",
   "type": "stat",
   "description": "Days until CPU usage reaches ${resource_usage_threshold}% of capacity.\nEstimated based on the last ${days_of_estimation} days of data.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(avg by (agent_hostname)(1*($resource_usage_threshold / 100) - (1 - avg(rate(node_cpu_seconds_total{agent_hostname=~\"$agent_hostname\", mode=\"idle\"}[5m]))))\n/\n(avg by (agent_hostname)(delta((1 - avg(rate(node_cpu_seconds_total{agent_hostname=~\"$agent_hostname\", mode=\"idle\"}[5m])))[${days_of_estimation}d:]) > 0 ) / $days_of_estimation ))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host - $agent_hostname",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "repeat": "agent_hostname",
   "collapsed": true,
   "panels": [
    {
     "title": "Days until  storage reaches ${resource_usage_threshold}%",
     "type": "stat",
     "description": "Days until  storage reaches ${resource_usage_threshold}%.\nEstimated based on the last ${days_of_estimation} days of data.",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(node_filesystem_size_bytes{agent_hostname=\"$agent_hostname\", device=~\"/dev/.*\"} * ($resource_usage_threshold / 100) - (node_filesystem_size_bytes{agent_hostname=\"$agent_hostname\", device=~\"/dev/.*\"}-node_filesystem_avail_bytes{agent_hostname=\"$agent_hostname\", device=~\"/dev/.*\"}))) \n/ \n((sum(delta((node_filesystem_size_bytes{agent_hostname=\"$agent_hostname\", device=~\"/dev/.*\"}-node_filesystem_avail_bytes{agent_hostname=\"$agent_hostname\", device=~\"/dev/.*\"})[${days_of_estimation}d:])) > 0) / $days_of_estimation)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk usage (total size: ${total_disk_machine} GB)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 7, "x": 4, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{agent_hostname=\"$agent_hostname\", fstype!=\"tmpfs\"} / 1024^3 )\n/\n(node_filesystem_size_bytes{agent_hostname=\"$agent_hostname\", fstype!=\"tmpfs\"} / 1024^3)) * 100",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Memory usage (total memory: $total_memory GB)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 7, "x": 11, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "node_memory_MemUsed_percentage{agent_hostname=\"$agent_hostname\"}",
       "legendFormat": "Total memory used"
      },
      {
       "expr": "((node_memory_HugePages_Total{agent_hostname=~\"$agent_hostname\"} * node_memory_Hugepagesize_bytes{agent_hostname=~\"$agent_hostname\"}) / (node_memory_MemTotal_bytes{agent_hostname=\"$agent_hostname\"})) * 100",
       "legendFormat": "Memory assigned to hugepages"
      },
      {
       "expr": "(((node_memory_HugePages_Total{agent_hostname=~\"$agent_hostname\"} * node_memory_Hugepagesize_bytes{agent_hostname=~\"$agent_hostname\"}) - (node_memory_HugePages_Free{agent_hostname=~\"$agent_hostname\"} * node_memory_Hugepagesize_bytes{agent_hostname=~\"$agent_hostname\"})) / (node_memory_MemTotal_bytes{agent_hostname=\"$agent_hostname\"})) * 100",
       "legendFormat": "Used hugepages memory"
      }
     ]
    },
    {
     "title": "CPU Usage (total number of cores: $cpu_count)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "label_replace((1 - avg(rate(node_cpu_seconds_total{agent_hostname=\"$agent_hostname\",mode=\"idle\"}[5m]))) * 100, \"__name__\", \"$agent_hostname\", \"__name__\", \"\")",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Days until memory reaches ${resource_usage_threshold}%",
     "type": "stat",
     "description": "Days until memory reaches ${resource_usage_threshold}% of capacity.\nEstimated based on the last ${days_of_estimation} days of data.",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(100 * ($resource_usage_threshold / 100) - (node_memory_MemUsed_percentage{agent_hostname=\"$agent_hostname\"}))\n/ \n((delta((node_memory_MemUsed_percentage{agent_hostname=\"$agent_hostname\"})[${days_of_estimation}d:]) > 0) / $days_of_estimation)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Days until CPU usage reaches ${resource_usage_threshold}% ",
     "type": "stat",
     "description": "Days until CPU usage reaches ${resource_usage_threshold}% of capacity.\nEstimated based on the last ${days_of_estimation} days of data.",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(1*($resource_usage_threshold / 100) - (1 - avg(rate(node_cpu_seconds_total{agent_hostname=\"$agent_hostname\", mode=\"idle\"}[5m]))))\n/\n(avg(delta((1 - avg(rate(node_cpu_seconds_total{agent_hostname=\"$agent_hostname\", mode=\"idle\"}[5m])))[${days_of_estimation}d:]) > 0) / $days_of_estimation )",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}