{
 "title": "OpenStack Logging",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "juju_unit",
    "label": "Juju unit",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_application=~\"$juju_application\"},juju_unit)"
    }
   },
   {
    "name": "juju_application",
    "label": "Juju application",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\"},juju_application)"
    }
   },
   {
    "name": "juju_model_uuid",
    "label": "Juju model uuid",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\"},juju_model_uuid)"
    }
   },
   { "name": "juju_model", "label": "Juju model", "query": { "query": "label_values(up,juju_model)" } },
   { "name": "lokids", "label": "Loki datasource", "query": "loki" },
   { "name": "prometheusds", "label": "Prometheus datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1m, 5m, 10m, 30m, 1h" },
   { "name": "request_id", "label": "Request ID" },
   { "name": "severity", "label": "Severity", "query": "OKAY, WARNING, ERROR" },
   {
    "name": "service",
    "label": "Service",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "OpenStack Service Logs",
   "type": "logs",
   "description": "The logs of OpenStack service.\n\nThe logs can be filtered by \"Request ID\" using the dashboard variable. \n\nFor the log context, click on the \"Explore\" button in the panel drop down. ",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{juju_model=\"openstack\", pebble_service=~\".+\"} |~ \"$request_id\" | pattern \"<_>-<_>-<_> <_>:<_>:<_>.<_> <_> <_> <_> [<_>] <message>\" | message != \"\" | line_format `{{ printf \"%25.25s in %-20.20s %s\" .pebble_service .juju_unit .message}}`"
    },
    {
     "expr": "{filename=\"/var/log/syslog\"} |~ \"$request_id\" | pattern `<_> <_> <_>:<_>:<_> <hostname> <application>[<_>]: <_>-<_>-<_> <_>:<_>:<_>.<_> <_> <_> <_> [<_>] <message>` | message != \"\" | line_format `{{ printf \"%25.25s in %-20.20s %s\" .application .hostname .message}}`"
    }
   ]
  },
  {
   "title": "OpenStack Internal and Public Interfaces HTTP status code (Overview)",
   "type": "timeseries",
   "description": "The overview of the counts of HTTP status code per second for OpenStack internal and public interfaces. \n\n\"severity=OKAY\" implies a status code in [100-399]\n\"severity=WARNING\" implies a status code in [400-499]\n\"severity=ERROR\" implies a status code in [500-599]\n",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by (severity) (\n    label_replace(\n        rate(traefik_service_requests_total{juju_model=\"openstack\", code=~\"(1|2|3)..\"}[$interval]) > 0\n        , \"severity\", \"severity=OKAY\", \"\", \"\"\n    )\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (severity) (\n    label_replace(\n        rate(traefik_service_requests_total{juju_model=\"openstack\", code=~\"4..\"}[$interval]) > 0\n        , \"severity\", \"severity=WARNING\", \"\", \"\"\n    )\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (severity) (\n    label_replace(\n        rate(traefik_service_requests_total{juju_model=\"openstack\", code=~\"5..\"}[$interval]) > 0\n        , \"severity\", \"severity=ERROR\", \"\", \"\"\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OpenStack API HTTP status code (Overview)",
   "type": "timeseries",
   "description": "The overview of the counts of HTTP status code per second for OpenStack API. \n\nFor the log samples, click on the \"Explore\" button in the panel drop down.\n\n\"severity=OKAY\" implies a status code in [100-399]\n\"severity=WARNING\" implies a status code in [400-499]\n\"severity=ERROR\" implies a status code in [500-599]\n",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "topk (15, \n    sum by (severity) (\n        rate(\n            {pebble_service=~\"wsgi-.+|glance-api|neutron-server\"} | \n            pattern `<_> \"<_>\" severity: <status_code_a> <_>` | \n            pattern `<_> \"<_>\" <status_code_b> <_>`| \n            status_code_a =~ \"(1|2|3)..\" or status_code_b =~ \"(1|2|3)..\" | \n            label_format severity=\"OKAY\" \n            [$interval]\n        )\n    )\n)"
    },
    {
     "expr": "topk (15, \n    sum by (severity) (\n        rate(\n            {pebble_service=~\"wsgi-.+|glance-api|neutron-server\"} | \n            pattern `<_> \"<_>\" severity: <status_code_a> <_>` | \n            pattern `<_> \"<_>\" <status_code_b> <_>`| \n            status_code_a =~ \"4..\" or status_code_b =~ \"4..\" | \n            label_format severity=\"WARNING\" \n            [$interval]\n        )\n    )\n)"
    },
    {
     "expr": "topk (15, \n    sum by (severity) (\n        rate(\n            {pebble_service=~\"wsgi-.+|glance-api|neutron-server\"} | \n            pattern `<_> \"<_>\" severity: <status_code_a> <_>` | \n            pattern `<_> \"<_>\" <status_code_b> <_>`| \n            status_code_a =~ \"5..\" or status_code_b =~ \"5..\" | \n            label_format severity=\"ERROR\" \n            [$interval]\n        )\n    )\n)"
    }
   ]
  },
  {
   "title": "OpenStack API HTTP status code by severity ($severity) - aggregate view",
   "type": "timeseries",
   "description": "The counts of different HTTP status code per second grouped by severity for each OpenStack service. \n\nThe service can be filtered by the \"Service\" variable.\n\nThe severity can be filtered by the \"Severity\" variable.\n\nFor the log samples, click on the \"Explore\" button in the panel drop down.\n\n\"severity=OKAY\" implies a status code in [100-399]\n\"severity=WARNING\" implies a status code in [400-499]\n\"severity=ERROR\" implies a status code in [500-599]\n",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "topk (15, \n    sum by (juju_unit, pebble_service, severity) (\n        rate(\n            {pebble_service=~\"wsgi-.+|glance-api|neutron-server\"} | \n            pebble_service =~ \"$service\" |\n            pattern `<_> \"<_>\" status: <status_code_a> <_>` | \n            pattern `<_> \"<_>\" <status_code_b> <_>` | \n            status_code_a =~ \"(1|2|3)..\" or status_code_b =~ \"(1|2|3)..\" | \n            label_format severity=\"OKAY\" | severity =~ \"$severity\" | \n            label_format status_code=`{{if .status_code_a}}{{.status_code_a}}{{else}}{{.status_code_b}}{{end}}`\n            [$interval]\n        )\n    )\n)"
    },
    {
     "expr": "topk (15, \n    sum by (juju_unit, pebble_service, severity) (\n        rate(\n            {pebble_service=~\"wsgi-.+|glance-api|neutron-server\"} | \n            pebble_service =~ \"$service\" |\n            pattern `<_> \"<_>\" status: <status_code_a> <_>` | \n            pattern `<_> \"<_>\" <status_code_b> <_>` | \n            status_code_a =~ \"4..\" or status_code_b =~ \"4..\" | \n            label_format severity=\"WARNING\" | severity =~ \"$severity\" | \n            label_format status_code=`{{if .status_code_a}}{{.status_code_a}}{{else}}{{.status_code_b}}{{end}}` \n            [$interval]\n        )\n    )\n)"
    },
    {
     "expr": "topk (15, \n    sum by (juju_unit, pebble_service, severity) (\n        rate(\n            {pebble_service=~\"wsgi-.+|glance-api|neutron-server\"} | \n            pebble_service =~ \"$service\" |\n            pattern `<_> \"<_>\" status: <status_code_a> <_>` | \n            pattern `<_> \"<_>\" <status_code_b> <_>` | \n            status_code_a =~ \"5..\" or status_code_b =~ \"5..\" | \n            label_format severity=\"ERROR\" | severity =~ \"$severity\" | \n            label_format status_code=`{{if .status_code_a}}{{.status_code_a}}{{else}}{{.status_code_b}}{{end}}`\n            [$interval]\n        )\n    )\n)"
    }
   ]
  },
  {
   "title": "OpenStack API HTTP status code by severity ($severity) - breakdown view",
   "type": "timeseries",
   "description": "The counts of different HTTP status code per second for each OpenStack service.\n\nThe service can be filtered by the \"service\" variable.\n\nThe severity can be filtered by the \"severity\" variable.\n\nFor the log samples, click on the \"Explore\" button in the panel drop down.\n\n\"severity=OKAY\" implies a status code in [100-399]\n\"severity=WARNING\" implies a status code in [400-499]\n\"severity=ERROR\" implies a status code in [500-599]\n",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "topk (15, \n    sum by (juju_unit, pebble_service, status_code) (\n        rate(\n            {pebble_service=~\"wsgi-.+|glance-api|neutron-server\"} | \n            pebble_service =~ \"$service\" |\n            pattern `<_> \"<_>\" status: <status_code_a> <_>` | \n            pattern `<_> \"<_>\" <status_code_b> <_>` | \n            status_code_a =~ \"(1|2|3)..\" or status_code_b =~ \"(1|2|3)..\" | \n            label_format severity=\"OKAY\" | severity =~ \"$severity\" |\n            label_format status_code=`{{if .status_code_a}}{{.status_code_a}}{{else}}{{.status_code_b}}{{end}}`\n            [$interval]\n        )\n    )\n)"
    },
    {
     "expr": "topk (15, \n    sum by (juju_unit, pebble_service, status_code) (\n        rate(\n            {pebble_service=~\"wsgi-.+|glance-api|neutron-server\"} |\n            pebble_service =~ \"$service\" | \n            pattern `<_> \"<_>\" status: <status_code_a> <_>` | \n            pattern `<_> \"<_>\" <status_code_b> <_>` | \n            status_code_a =~ \"4..\" or status_code_b =~ \"4..\" | \n            label_format severity=\"WARNING\" | severity =~ \"$severity\" | \n            label_format status_code=`{{if .status_code_a}}{{.status_code_a}}{{else}}{{.status_code_b}}{{end}}`\n            [$interval]\n        )\n    )\n)"
    },
    {
     "expr": "topk (15, \n    sum by (juju_unit, pebble_service, status_code) (\n        rate(\n            {pebble_service=~\"wsgi-.+|glance-api|neutron-server\"} | \n            pebble_service =~ \"$service\" |\n            pattern `<_> \"<_>\" status: <status_code_a> <_>` | \n            pattern `<_> \"<_>\" <status_code_b> <_>` | \n            status_code_a =~ \"5..\" or status_code_b =~ \"5..\" | \n            label_format severity=\"ERROR\" | severity =~ \"$severity\" | \n            label_format status_code=`{{if .status_code_a}}{{.status_code_a}}{{else}}{{.status_code_b}}{{end}}`\n            [$interval]\n        )\n    )\n)"
    }
   ]
  }
 ]
}