groups:
- name: Neutron
  rules:
    - alert: NeutronStateCritical
      expr: openstack_neutron_agent_state == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: Neutron service down. (Instance {{ $labels.hostname }})
        description: |
          The Neutron service is currently down on host {{ $labels.hostname }}.
            LABELS = {{ $labels }}
