external-libraries:
  - charms.data_platform_libs.v0.data_interfaces
  - charms.rabbitmq_k8s.v0.rabbitmq
  - charms.traefik_k8s.v2.ingress
  - charms.certificate_transfer_interface.v0.certificate_transfer
  - charms.loki_k8s.v1.loki_push_api
  - charms.tempo_k8s.v2.tracing
  - charms.tempo_k8s.v1.charm_tracing
  - charms.hydra.v0.oauth
  - charms.kratos_external_idp_integrator.v0.kratos_external_provider
internal-libraries:
  - charms.horizon_k8s.v0.trusted_dashboard
templates:
  - parts/section-database
  - parts/database-connection
  - parts/database-connection-settings
  - parts/section-middleware
  - parts/section-oslo-cache
  - parts/section-oslo-messaging-rabbit
  - parts/section-oslo-middleware
  - parts/section-oslo-notifications
  - parts/section-signing
