external-libraries:
  - charms.operator_libs_linux.v2.snap
  - charms.data_platform_libs.v0.data_interfaces
  - charms.rabbitmq_k8s.v0.rabbitmq
  - charms.certificate_transfer_interface.v0.certificate_transfer
  - charms.loki_k8s.v1.loki_push_api
  - charms.tempo_k8s.v2.tracing
  - charms.tempo_k8s.v1.charm_tracing
internal-libraries:
  - charms.keystone_k8s.v0.identity_credentials
templates: []
