external-libraries:
  - charms.loki_k8s.v1.loki_push_api
  - charms.tempo_coordinator_k8s.v0.tracing
  - charms.tempo_coordinator_k8s.v0.charm_tracing
internal-libraries:
  - charms.keystone_k8s.v0.domain_config
