external-libraries:
  - charms.data_platform_libs.v0.data_interfaces
  - charms.traefik_k8s.v2.ingress
  - charms.tls_certificates_interface.v4.tls_certificates
  - charms.certificate_transfer_interface.v0.certificate_transfer
  - charms.loki_k8s.v1.loki_push_api
  - charms.tempo_k8s.v2.tracing
  - charms.tempo_k8s.v1.charm_tracing
internal-libraries:
  - charms.keystone_k8s.v1.identity_service
  - charms.keystone_k8s.v0.identity_resource
  - charms.ovn_central_k8s.v0.ovsdb
  - charms.designate_k8s.v0.designate_service
templates:
  - parts/section-database
  - parts/database-connection
  - parts/database-connection-settings
  - parts/section-identity
  - parts/identity-data
  - ca-bundle.pem.j2
