# This file defines charm config options, and populates the Configure tab on Charmhub.
# If your charm does not require configuration options, delete this file entirely.
#
# See https://juju.is/docs/config for guidance.
options:
  debug:
    default: False
    type: boolean
  http_proxy:
    description: Set HTTP_PROXY in /etc/environment
    type: string
  https_proxy:
    description: Set HTTPS_PROXY in /etc/environment
    type: string
  no_proxy:
    description: Set NO_PROXY in /etc/environment
    type: string
