- name: charm is packed
  command:
    cmd: "{{ tox_executable }} -e build -- {{ charm_build.path }}"
    chdir: "{{ zuul.project.src_dir }}"
  register: res
  retries: 3
  delay: 30
  until: >
    "Charm packed ok" in res.stdout
  failed_when: '"Failed instance creation" in res.stdout'

- name: charmcraft packing environment is cleaned
  command:
    cmd: charmcraft clean
    chdir: "{{ zuul.project.src_dir }}/charms/{{ charm_build.path }}"
