external-libraries:
  - charms.operator_libs_linux.v2.snap
  - charms.tls_certificates_interface.v4.tls_certificates
  - charms.tempo_coordinator_k8s.v0.tracing
  - charms.tempo_coordinator_k8s.v0.charm_tracing
