- name: Set charm name fact
  set_fact:
    charm_name: "{{ (zuul.job | default('')).removeprefix('publish-charm-') }}"

- name: Download charms tarball (artifact from gate pipeline)
  include_role:
    name: download-artifact
  vars:
    download_artifact_api: "https://zuul.opendev.org/api/tenant/{{ zuul.tenant }}"
    download_artifact_type: charm_archive
    download_artifact_pipeline: gate
    download_artifact_job: charm-build-watchtower
    download_artifact_directory: "{{ zuul.project.src_dir }}"

- name: Extract charms tarball
  unarchive:
    src: "{{ zuul.project.src_dir }}/charms.tar.gz"
    dest: "{{ zuul.project.src_dir }}"
    remote_src: true

- name: Find downloaded charm files
  find:
    paths: "{{ zuul.project.src_dir }}/artifacts"
    patterns: "*.charm"
    recurse: true
  register: charm_files

- name: Copy charm files to project src dir
  copy:
    src: "{{ item.path }}"
    dest: "{{ zuul.project.src_dir }}/{{ item.path | basename }}"
    remote_src: true
  loop: "{{ charm_files.files }}"

- name: Get all downloaded charm names
  args:
    chdir: "{{ zuul.project.src_dir }}"
    executable: /bin/bash
  shell: |
    charms=$(ls *.charm | sed 's/_[^.]*\.charm$//' | sort -u)
    if [[ $? != 0 ]]; then
        echo ""
    else
       echo "$charms"
    fi
  register: built_charms

- name: Prepare charm channel dict for downloaded charms
  set_fact:
    charm_channels: "{{ charm_channels | default({}) | combine({item.key: item.value}) }}"
  loop: "{{ lookup('ansible.builtin.dict', publish_channels) }}"
  when: "{{ item.key in built_charms.stdout_lines }}"

- name: Print charm channel dict
  debug:
    msg: "Charms to be published: {{ charm_channels | default({}) }}"

- name: Publish charms in a loop
  include_tasks: "publish.yaml"
  vars:
    charm_build_name: "{{ channel.key }}"
    publish_channel: "{{ channel.value }}"
  loop: "{{ charm_channels | default({}) | dict2items }}"
  loop_control:
    loop_var: channel
