external-libraries:
  - charms.loki_k8s.v1.loki_push_api
  - charms.tempo_coordinator_k8s.v0.tracing
  - charms.tempo_coordinator_k8s.v0.charm_tracing
  - charms.operator_libs_linux.v2.snap
internal-libraries:
  - charms.cinder_volume.v0.cinder_volume
